version: 1
disable_existing_loggers: false
formatters:
  ecs:
    class: ecs_logging.StdlibFormatter
handlers:
  default:
    class: logging.StreamHandler
    formatter: ecs
    stream: ext://sys.stdout
loggers:
  uvicorn:
    handlers: [default]
    level: DEBUG
    propagate: false
  uvicorn.error:
    handlers: [default]
    level: DEBUG
    propagate: false
  uvicorn.access:
    handlers: [default]
    level: DEBUG
    propagate: false
root:
  handlers: [default]
  level: DEBUG
